version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: prismagov_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prismagov
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: prismagov_gotenberg
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  postgres_data:
