# ✅ ATUALIZADO: Usa a imagem oficial para Node.js v20 (LTS mais recente).
FROM mcr.microsoft.com/devcontainers/javascript-node:0-20

# Instala o NestJS CLI e o Prisma globalmente para fácil acesso
RUN su node -c "npm install -g @nestjs/cli prisma"
